jsxc/jsxc

jsxc.css, jsxc.lib.js
=> Display the timestamp of messages

jsxc.lib.js
=> Avoid duplicate window list

.gitignore, Gruntfile.js, bower.json, dep.json, img/bookmark_red.svg, locales/de.json, locales/el.json, locales/en.json, locales/es.json, locales/fr.json, locales/it.json, locales/nds.json, locales/pl.json, locales/pt-BR.json, locales/ro.json, locales/ru.json, scss/_buddylist.scss, src/jsxc.lib.gui.js, src/jsxc.lib.muc.js, src/jsxc.lib.xmpp.bookmarks.js, src/jsxc.lib.xmpp.js, template/bookmarkDialog.html, template/joinChat.html
This pull request implements [XEP-0048](https://xmpp.org/extensions/xep-0048.html) #165.
=> [WIP] load bookmarks and attach remove handler

package.json
=> Forcing node-sass to version 3.3.0, fix #244

src/jsxc.lib.gui.js
Pull request for #401 
I have applied the patch to the current master and pushed it as a branch here. I made sure, that the same patch works nicely on jsxc.js-3.0.1.
I have NOT rebuild/tested this directly.
=> showLoginBox: Improve initial focus (fix #401)

scss/_window.scss, src/jsxc.lib.gui.js, template/chatWindow.html
@ChristianTacke @thfree please test and verify if possible
Line breaks are possible with shift+enter.
=> Multiline message

src/jsxc.lib.fileTransfer.js, src/jsxc.lib.xmpp.httpUpload.js
fix #457
@PeterEdens @ChristianTacke can you verify that this fix works for you or that this fix does not break anything for you?
=> fix http upload discovery

bower.json
=> Fix remote bookmark storage

Gruntfile.js, src/jsxc.lib.gui.avatar.js, src/jsxc.lib.gui.js, src/jsxc.lib.js, src/jsxc.lib.options.js, src/jsxc.lib.xmpp.js
@ArnY maybe you want to test this enhancements.
=> Roster enhancements

scss/_muc.scss, src/jsxc.lib.fileTransfer.js, src/jsxc.lib.muc.js
fix #535
@peterhoth can you test this?
=> enable http upload for muc

src/jsxc.lib.Message.js, src/jsxc.lib.xmpp.httpUpload.js, src/jsxc.lib.xmpp.js
fix #526 fix #534
@PeterEdens can you test this?
=> fix thumbnail transfer

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
@MarcelWaldvogel @LEDfan @DanScharon your opinions on this topic?
=> add code of conduct

src/jsxc.lib.webrtc.js
close #545
This needs some testing.
@puuu once again, great work :+1:.
=> use external service discovery for ice server retrieval

src/jsxc.lib.gui.js, src/jsxc.lib.js, src/jsxc.lib.xmpp.js
=> add automatic login

src/jsxc.lib.gui.js
I would have loved to see the bare JID in the chat windows. Here is one hack to do it.
Would you prefer an alternate translation string instead?
=> Say who is online

src/jsxc.lib.xmpp.mam.js
@MarcelWaldvogel please test this
=> support mam:1

src/Message.interface.ts, src/Message.ts, src/Transcript.ts, src/connection/AbstractConnection.ts, src/plugin/PluginAPI.interface.ts, src/plugin/PluginAPI.ts, src/plugins/MeCommandPlugin.ts, src/plugins/mam/Archive.ts, src/plugins/mam/Plugin.ts, src/plugins/otr/Plugin.ts, src/ui/ChatWindow.ts, src/ui/ChatWindowMessage.ts
fix #796
@jlemangarin please test and verify that this fix works
=> Fix MAM retrieval

package.json, src/connection/xmpp/ConnectHelper.ts, yarn.lock
=> Change strophe types package

src/UserMedia.ts, src/ui/actions/call.ts
screen sharing call without voice is useless
=> feat: add audio stream for screen share stream.

locales/bn-BD.json, locales/de.json, locales/en.json, scss/partials/_dialog.scss, scss/partials/_muc.scss, src/CONST.ts, src/connection/Connection.interface.ts, src/connection/services/MUC.ts, src/ui/MultiUserChatWindow.ts, src/ui/dialogs/multiUserMemberlist.ts, template/multiUserMemberlist.hbs
[xep-0045 9.5 Modifying the member list](https://xmpp.org/extensions/xep-0045.html#modifymember)
=> add menu to add/delete members from memberlist

src/ui/Roster.ts
to prevent connection loss if help is opened in same tab
=> open help in new tab/window

scss/partials/_jsxc.scss, template/chatWindowList.hbs, template/dialog.hbs, template/roster.hbs
@mightymop can you test if this fixes your out-of-window issue? Maybe also your hidden lock icon?
fix #972
fix #968
=> fix: use border-box

scss/partials/_menu.scss, src/ui/Roster.ts
- If there are more than ~ 25 unread notifications the
clear all menu item is not reachable, because the menu is noch scrollable.
=> fix: fix clear all notifications menuentry at bottom

locales/bn-BD.json, locales/de.json, locales/en.json, scss/partials/_dialog.scss, src/connection/AbstractConnection.ts, src/connection/Connection.interface.ts, src/connection/Form.ts, src/connection/services/Search.ts, src/ui/Roster.ts, src/ui/dialogs/contact.ts, src/ui/dialogs/contactsearch.ts, template/contact.hbs, template/contactsearch.hbs
[XEP-0055: Jabber Search](https://xmpp.org/extensions/xep-0055.html)
=> XEP-0055 - Add User Search

images/placeholder_image.svg, locales/de.json, locales/en.json, src/OptionsDefault.ts, src/connection/xmpp/handlers/chatMessage.ts, src/plugins/httpUpload/HttpUploadPlugin.ts, src/ui/ChatWindowMessage.ts, src/ui/dialogs/settings.ts
show image links as attachement and open links in new tab by setting target=_blank on links
fix #911
=> open links in new tab/window and load image urls

src/plugins/omemo/Plugin.ts
If a omemo session in a chatbox is initiated by the user, the keys and devicelist are now loaded from a pep service on another server (server 2 server connection) too.
=> fix omemo key loading from s2s servers

locales/en.json, scss/partials/_dialog.scss, src/MultiUserContact.ts, src/ui/DialogSection.ts, src/ui/dialogs/settings.ts
fix: link to corresponding XEP reference
feat: add more XEP Infos and collapsibles
fix: uncheck and disable checkbox for omemo plugin if libsignal is not available
close: #974
=> Enhance Settings

locales/en.json, src/OptionsDefault.ts, src/bootstrap/plugins.ts, src/connection/storage/Connection.ts, src/plugin/PluginAPI.interface.ts, src/plugin/PluginAPI.ts, src/plugins/VersionPlugin.ts
add [XEP-0092](https://xmpp.org/extensions/xep-0092.html) as a Plugin
At this time the plugin only reacts on querys from other clients/server.
May be we could improve it to query others for information and show theese on vcard dialog.
=> feat: XEP-0092 Software Version

webpack.config.js
=> fix: webpack config error

scss/partials/_dialog.scss, scss/partials/_layout.scss, scss/partials/_roster.scss
fix https://github.com/jsxc/jsxc/issues/1048
=> style: fix darkmode

src/connection/services/Vcard.ts, src/plugins/VersionPlugin.ts, src/plugins/mam/Plugin.ts, src/plugins/omemo/Plugin.ts, src/ui/ChatWindow.ts
and show button, if chat history was cleared
fix: if chatwindow area was dragged bigger than the scoll did not show the button if top was reached...
=> feat: show "Load Button" if message area is empty
