- example/index.html
- example/login.html
Greetings, Klaus. Please forgive me if I overlooked something in the directory design, but in my experience, the currently given locations of jsxc*.js in ./example/*.html are incorrect and as a result, the examples will not work without this patch.
> Update jsxc*.js <script src= location in ./example

- src/jsxc.lib.options.js
- src/jsxc.lib.webrtc.js
To be able to work cross-domain, the destination domain need CORS to be
properly configured. withCredentials means that cookie are send then
performing the ajax call, allowing all kind of cookie based authentication.
> Use crendential when performing turn credential ajax crossdomain call.

- src/jsxc.lib.webrtc.js
Method MediaStream.stop has been [deprecated](https://developers.google.com/web/updates/2015/07/mediastream-deprecations#stop-ended-and-active) since Google Chrome 45 in favor of stopping each track individually.
> Stop each MediaStreamTrack individually

- src/jsxc.lib.webrtc.js
Here's bug: auto-accept does not start the video/audio stream, i.e. it opens call window, but no multimedia data is sent.
> Fix auto-accept

- .gitignore
- bower.json
Correct me if I'm wrong, but since all dependencies are also bundled in the build directory, there is no need for these to be marked as dependencies.
Marking them as devDependencies makes sure that these (rather huge) libraries are not included when including jsxc in other projects.
> Bower dependencies are actually devDependencies

- src/jsxc.lib.gui.js
If the server is returning entries slower than the user is entering
additional characters, the callback gets executed multiple times after,
the list has been cleared - resulting in the same entries being appended
multiple times.
> Clear userlist before appending entries from "getUsers" result.

- .hound.yml
- .scss-lint.yml
- img/bell.svg
- locales/el.json
- locales/en.json
- locales/es.json
- locales/fi.json
- locales/fr.json
- locales/hu-HU.json
- locales/it.json
- locales/nds.json
- locales/pl.json
- locales/pt-BR.json
- locales/ro.json
- locales/ru.json
- locales/tr-TR.json
- locales/zh-TW.json
- locales/zh.json
- scss/_jsxc.scss
- scss/_webrtc.scss
- scss/_window.scss
- src/jsxc.lib.gui.js
- src/jsxc.lib.options.js
- src/jsxc.lib.webrtc.js
- template/confirmDialog.html
- template/incomingCall.html
- template/videoWindow.html
fix #8
There are some browser limitations for desktop sharing:
- support only in chrome and firefox with custom extension
- every domain which requests screen media, needs his own extension
- example extension can be found at https://github.com/otalk/getScreenMedia
- requires https
**TODO**
> [WIP] Add desktop sharing

- src/jsxc.lib.xmpp.chatState.js
Fix the following bug: when one user is writing a message, its name is missing in the composing message in the chat/groupchat window of the other(s) user(s)
> A little bug: user name missing in the composing message

- src/jsxc.lib.xmpp.js
fix the i18n key used when informing about a message coming from an unknown sender
> Non translated text about the receipt of a message from an unknown sender

- src/jsxc.lib.xmpp.js
Before this commit https://github.com/jsxc/jsxc/commit/487e32a7b9a676e7527e96fccc9d7d748c02437a#diff-4e5734936042c4309a95a260fd764feaL3328 the condition would be send. Currently the `jsxc.xmpp.onConnfail` tries to uses this condition, but instead logs `undefined`.
This would be very useful for https://github.com/nextcloud/jsxc.nextcloud/pull/57
> Send Condition on connfail so custom handlers can check it

- locales/de.json
Hey,
I found a spelling error in the German localisation. I want trying to fix it on my own. Hope this is the right way to do. The second change at the end was done automatically I think.
Regards,
C.
> mehereren -> mehreren

- src/Message.ts
When marking quotations, we loop into the typed lines.
In some configurations, the for loop set the lineNumber to 'last' at the end, so the line can't be retrieved and an undefined error is triggered in the "line.indexOf' part.
> Prevent undefined 'last' key in array loop when marking quotations

- src/connection/Form.ts
- src/connection/FormField.ts
- src/connection/FormItemField.ts
- src/connection/FormReportedField.ts
- src/errors/ParsingError.ts
working on XEP-0004: Data Forms compliance. Currently only parsing from XML and checking integrity is implemented. Detailed description:
- parsing 'reported' and 'item' fields in 'fromXML
- check compliance/integrity in 'checkItems'
- moved 'Field' class to dedicated file to reduce clutter
- added 'ReportedField' and 'ItemField' classes to prepare for easier conversion
- added 'ParsingError' (unused)
> parse reported and item elements in form

- src/MultiUserContact.ts
The wrong argument is passed to the super class Contact in the constructor of the MUC class so the display name is not taken into account
> fix: display name of muc rooms is not taken into account

- src/MultiUserContact.ts
- src/plugins/bookmarks/BookmarkProvider.ts
- src/plugins/bookmarks/RoomBookmark.ts
- src/plugins/bookmarks/services/LocalService.ts
- src/plugins/bookmarks/services/PubSubService.ts
Ref : https://xmpp.org/extensions/attic/xep-0048-1.0.html part 2.2
The "password" sub-element should be stored when it's present in the contact data (refer to https://github.com/jsxc/jsxc/pull/807)
> feat: password sub element in bookmark storage for conference element

- src/ui/dialogs/multiUserJoin.ts
Jitsi has speakerstats_component which is not support getting discoinfo and responses with 
```xml
<iq xmlns="jabber:client" type="error" to="as@site.com/jsxc-6e71fee0" from="speakerstats.site.com" id="4bcd4257-0c2a-423a-b458-60b3d9079b8d:sendIQ">
<error type="cancel">
<service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
</error>
</iq>
```
which is stopping searching for MUC component domain.
Following change set allows to ignore ``service-unavailable`` for components which does not support disco items request and will re-throw ``stanza`` item in something else happend.
> fix: ignore components which does not support DiscoInfo on determining MUC services at XMPP server

- src/Contact.ts
- src/plugins/omemo/Plugin.ts
- src/plugins/otr/Plugin.ts
- src/plugins/otr/Session.ts
When trying to turn on / off some encryption plugin you will get in console 
```plain
Uncaught Error: Couldn't find omemo
at PluginRepository.getEncryptionPlugin (PluginRepository.ts:81)
at HTMLDivElement.eval (ChatWindow.ts:474)
at HTMLDivElement.dispatch (jquery.min.js:2)
at HTMLDivElement.y.handle (jquery.min.js:2)
```
OMEMO was not working - well messages was not encrypted and was send as plain text. 
since ```PluginRepository.getEncryptionPlugin ``` moved to method ```getID()``` so changed rest parts .
> fix:  use getId() for checking set encryption state

- src/ui/ChatWindowFileTransferHandler.ts
JSXC is great! I'd like to help JSXC stay awesome :) 
This merge hopefully resolves #856 via a paste event trigger from the chatWindow input. This event triggers a check if the clipboard contains an image. If so the clipboard is read in as a blob and processed using the existing methods for file uploading.
> feat: Added image paste feature (resolves #856)

- src/plugins/mam/Archive.ts
Issue is:
* User A and user B chat with each other, and a lot of messages archived to server
* User A use a new PC or web browser, or clear browser storage
* User B send user A message like "Hello"
* User A received message from user B "Hello", and click "Load history message"
* User A now received message "Hello" twice
Solve:
When get archived message, the query param "endDate" can be earlier than last message by 1 second, and wont miss any message.
> Fix duplicate message when load mam

- src/ui/dialogs/multiUserJoin.ts
- template/multiUserJoin.hbs
Englisch:
-ensure that if multiple muc services are given, that "conference" (which is normaly the default muc service)  is shown in input field
-furthermore sort the muc services by name
-add a list to server input which includes all muc services (double click if empty)
Deutsch:
-Stellt sicher, dass beim Vorhandensein mehrerer MUC Dienste, der "conference"-Dienst angezeigt wird.
("conference" ist normalerweise der Standard-Dienst für MUC).
-Sind weitere MUC-Dienste vorhanden werden diese an Hand der Domain alphabetisch sortiert.
-Die Liste der MUC-Dienste wird nach Doppelklick auf das leere Inputfeld angezeigt.
> improve muc join dialog

- scss/partials/_bar.scss
- scss/partials/_jsxc.scss
- src/ui/Roster.ts
- src/ui/RosterItem.ts
- src/ui/dialogs/vcard.ts
- template/roster-item.hbs
- template/vcard.hbs
Options:
- showTags: true = force Tag-text, false = circle with hover to show text
- blinkNewMessages: true = blinking avatar on new messages, false = no blinking
fix #77
this shows the roster groups as labels unter de statustext/lastmessages fields
multiple groups are joined in one line ... 
if there is to less place the string will be ellipsized and could be read by a mouseover action
> add Tags to Roster Item

- scss/partials/_window.scss
- src/plugins/chatMarkers/ChatMarkersPlugin.ts
- if message type = error no chatmarker should be sent / shown in UI
- increased the character space between the two checkmarks so the second one is more visible...
fix #1007
> fix: Chatmarker should take care on type of message
